version: "3.9"
services:
  rabbitmq-server:
    image: rabbitmq:3.8.12-rc.3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
        test: ["CMD", "rabbitmqctl", "status"]
        interval: 30s
        timeout: 5s
        retries: 3
  rabbitmq-test:
    image:  ghcr.io/barkardk/rabbitmq-client:latest
    command: >
       /bin/sh -c "while true; do sleep 20; ./mq_test; done"
    restart: on-failure
    depends_on:
      - rabbitmq-server
    links:
      - rabbitmq-server
    environment:
      - RABBITMQ_AMQP_CONN_STR=amqp://guest:guest@rabbitmq-server:5672/

